name: Build and Deploy Escalations Cron

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CONTAINER_REGISTRY: vizzhyacr.azurecr.io
      REPOSITORY_NAME: myapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get secrets from Key Vault
        id: get-secrets
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: vizzhyvault
          secrets: acr-username,acr-password,git-username,git-token,storage-sas

      - name: Export secrets as environment variables
        run: |
          echo "ACR_USERNAME=${{ steps.get-secrets.outputs.acr-username }}" >> $GITHUB_ENV
          echo "ACR_PASSWORD=${{ steps.get-secrets.outputs.acr-password }}" >> $GITHUB_ENV
          echo "GIT_USERNAME=${{ steps.get-secrets.outputs.git-username }}" >> $GITHUB_ENV
          echo "GIT_TOKEN=${{ steps.get-secrets.outputs.git-token }}" >> $GITHUB_ENV
          echo "STORAGE_SAS=${{ steps.get-secrets.outputs.storage-sas }}" >> $GITHUB_ENV

      - name: Azure CLI version
        run: az --version

      - name: Login to Azure Container Registry
        run: |
          echo "$ACR_PASSWORD" | docker login "$AZURE_CONTAINER_REGISTRY" --username "$ACR_USERNAME" --password-stdin

      - name: Set environment variables
        run: |
          COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c 1-7)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          IMAGE_TAG=build-${GITHUB_RUN_ID}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

   
      - name: Build Docker image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$REPOSITORY_NAME:$COMMIT_HASH .

      - name: Push Docker image to ACR
        run: |
          docker push $AZURE_CONTAINER_REGISTRY/$REPOSITORY_NAME:$COMMIT_HASH

      - name: Git Config
        run: |
          git config --global user.email "tejasp0902@gmail.com"
          git config --global user.name "$GIT_USERNAME"

      - name: Clone Helm charts repo
        run: |
          git clone https://$GIT_USERNAME:$GIT_TOKEN@bitbucket.org/vizzh/k8s-helm-charts-new.git -b main
          cd k8s-helm-charts-new/escalations-cron
          az storage blob download \
            --account-name vizzhystgacc \
            --container-name conimage \
            --name sed.sh \
            --file sed.sh \
            --sas-token "$STORAGE_SAS"
          chmod +x sed.sh
          bash sed.sh $COMMIT_HASH
          rm sed.sh
          cd ..
          git add -A
          git commit -m "escalations-cron values changed"
          git pull --rebase origin stage || git rebase --abort
          git push https://$GIT_USERNAME:$GIT_TOKEN@bitbucket.org/vizzh/k8s-helm-charts-new.git

      - name: Done
        run: echo "Pipeline Completed..."
